track <- read.table("C:\\Users\\Beans\\Desktop\\BRIDGE MAN\\Junior Year\\Spring Semester\\Applied Multivariate Analysis\\Data\\T1-9.dat", header = F, col.names = c("100m", "200m", "400m", "800m", "1500m", "3000m", "marathon"))
attach(track)
qqnorm(X100m)
qqnorm(X200m)
qqnorm(X400m)
qqnorm(X800m)
qqnorm(X1500m)
qqnorm(X3000m)
qqnorm(marathon)
pairs(~X100m + X200m + X400m + X800m + X1500m + X3000m + marathon, data = track)
seq <- 1:54
q2 <- qchisq((seq - .5)/54, df = 7)
d2 <- sort(country)
plot(q2, d2)
tmp <- qqnorm(X100m)
cor(tmp$x, tmp$y)
tmp <- qqnorm(X200m)
cor(tmp$x, tmp$y)
tmp <- qqnorm(X400m)
cor(tmp$x, tmp$y)
tmp <- qqnorm(X800m)
cor(tmp$x, tmp$y)
tmp <- qqnorm(X1500m)
cor(tmp$x, tmp$y)
tmp <- qqnorm(X3000m)
cor(tmp$x, tmp$y)
tmp <- qqnorm(marathon)
cor(tmp$x, tmp$y)
snow <- read.table("C:\\Users\\Beans\\Desktop\\BRIDGE MAN\\Junior Year\\Spring Semester\\Applied Multivariate Analysis\\Data\\T3-2.dat", header = F, col.names = c("x1", "x2"))
attach(snow)
plot(x1, x2, main = "Snow workload vs. snow duration", xlab = "Snow duration (hours)", ylab = "Snow workload (hours)")
library(MASS)
res <- boxcox(x1 ~ 1)
i <- which.max(res$y)
res$x[i]
qqnorm((x1^.06-1)/.06)
qqnorm(log(x1))
res <- boxcox(x2 ~ 1)
i <- which.max(res$y)
res$x[i]
qqnorm((x2^(-.71)-1)/(-.71))
qqnorm((x2^(-.5) - 1)/(-.5))
x <- matrix(c(2, 12, 8, 9, 6, 9, 8, 10), nrow = 4, byrow = T)
Xbar <- colMeans(x)
S <- var(x)
mu0 <- matrix(c(7, 11), nrow = 2, byrow = T)
T2 <- 4 %*% t(Xbar - mu0) %*% solve(S) %*% (Xbar - mu0)
T2
crit <- 3 * 2 / 2 * qf(.05, 2, 2, lower.tail = F)
crit
